# Generated by Django 3.0.6 on 2020-07-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_picturemodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Gallery.PictureCategoryModel'),
        ),
    ]
