# Generated by Django 3.0.6 on 2020-07-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=30),
        ),
    ]
