# Generated by Django 3.0.6 on 2020-07-17 21:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200717_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default=blog.models.getSlug, max_length=30),
        ),
    ]
